// flow-typed signature: 286db85dc71c6fd6c89c4a20ab34e061
// flow-typed version: <<STUB>>/wish_v^1.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wish/lib/wish' {
  declare module.exports: any;
}

declare module 'wish/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wish/index' {
  declare module.exports: $Exports<'wish'>;
}
declare module 'wish/index.js' {
  declare module.exports: $Exports<'wish'>;
}
declare module 'wish/lib/wish.js' {
  declare module.exports: $Exports<'wish/lib/wish'>;
}
declare module 'wish/test/test.js' {
  declare module.exports: $Exports<'wish/test/test'>;
}
